---
permalink: windows/concept_general_layout_and_configuration.html
sidebar: sidebar
keywords: general, layout, configuration, information, storage, disk, group
summary: You can find information about the recommended general database layouts and storage configurations to avoid issues related to disk groups, file types, and tablespaces.
---
= General layout and configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can find information about the recommended general database layouts and storage configurations to avoid issues related to disk groups, file types, and tablespaces.

* Do not include files from more than one type of SAN file system in your database.
+
All files making up a database must reside on the same type of file system.

* SnapManager requires a multiple of 4K block size.
* If you want to register SnapManager backups with Oracle Recovery Manager (RMAN), you must create RMAN-enabled profiles.

The following are some guidelines for volume separation:

* Data files for only one database must be in the volume.
* You must use separate volumes for each of the following file classifications: database binaries, data files, online redo log files, archived redo log files, and control files.
* You do not need to create a separate volume for temporary database files, because SnapManager does not back up temporary database files.

For more information, see the _SnapManager for Oracle Best Practices_.

*Related information*

http://media.netapp.com/documents/tr-3761.pdf[SnapManager for Oracle Best Practices: media.netapp.com/documents/tr-3761.pdf]
