---
permalink: windows/concept_limitations_related_to_oracle_database.html
sidebar: sidebar
keywords: limitation, oracle, database
summary: Before you start working with SnapManager, you must know the limitations related to Oracle Database.
---
= Limitations related to Oracle Database
:icons: font
:imagesdir: ../media/

[.lead]
Before you start working with SnapManager, you must know the limitations related to Oracle Database.

The limitations are as follows:

* SnapManager supports Oracle versions 10gR2, 11gR1, 11gR2 and 12__c__, but does not support Oracle 10gR1 as the repository or target database.
* SnapManager will not support the use of a SCAN IP address in place of a host name.
+
SCAN IP is a new feature in Oracle 11gR2.

* SnapManager does not support Oracle Cluster File System (OCFS).
* Support for Oracle Database 9i is deprecated from SnapManager 3.2.
* Support for Oracle Database 10gR2 (earlier than 10.2.0.5) is deprecated from SnapManager 3.3.1.

NOTE: Identify the different versions of Oracle databases supported by referring to the Interoperability Matrix.

*Related information*

http://support.netapp.com/NOW/products/interoperability/[Interoperability Matrix: support.netapp.com/NOW/products/interoperability]
