---
permalink: windows/task_freeing_backups.html
sidebar: sidebar
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, fuction, space, smo
summary: You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smo backup free command to free the backups.
---
= Freeing backups
:icons: font
:imagesdir: ../media/

[.lead]
You can free backups, which deletes the Snapshot copies without deleting the backup metadata. This function frees the space occupied by the backup. You can use the smo backup free command to free the backups.

For a backup to be eligible for freeing, you must ensure the following:

* Backup was successful
* Backup is not to be mounted
* Backup does not have clones
* Backup is not to be retained by using an unlimited retention policy
* Backup is not already freed

You can specify the -dump option as an optional parameter to collect the dump files after the successful or failed backup free operation.

. Enter the following command: smo backup free -profileprofile_name {-labellabel [data | -archivelogs] | -idid | -all} -force [-dump] [-quiet] [-force]

*Related information*

xref:reference_the_smosmsapbackup_free_command.adoc[The smo backup free command]
