---
permalink: windows/task_order_of_performing_operations.html
sidebar: sidebar
keywords: snapmanager, enable, perform, operation, backup, cloning, clone, operation, order, perform
summary: SnapManager enables you to perform various operations such as creating profiles, performing backups, and cloning backups. These operations must be performed in a specific order.
---
= Order of performing operations
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager enables you to perform various operations such as creating profiles, performing backups, and cloning backups. These operations must be performed in a specific order.

. Create a profile on an existing repository by using the smo profile create command.
+
NOTE: The Oracle user specified for the target database must have sysdba privileges.
+
The following example shows the command to create a profile:
+
----
smo profile create -profile prof1 -profile-password prof1cred
-repository -dbname HR1 -login -username admin -host server1 -port 1521
-database -dbname dedb -login -username db_oper2
-password dbpw1 -host server1 -port 1521
----

. Create a backup on an existing profile by using the smo backup create command.
+
The following example shows the command to create a backup:
+
----
smo backup create -profile prof1 -full -offline -label full_backup_prof1 -force
----

. Restore and recover a database backup on primary storage by using the smo backup restore command.
+
The following example shows the command to restore a backup:
+
----
smo backup restore -profile prof1 -label full_backup_prof1
-complete -recover -alllogs
----

. Create a clone specification by using the smo clone template command.
+
You can use the Clone wizard in the graphical user interface (GUI) to create a template clone specification. You can also create the clone specification file by using a text editor.

. Clone a database with an existing backup by using the smo clone create command.
+
You must have an existing clone specification or create a clone specification to specify the storage and database specifications for the clone.
+
The following example shows the command to create a clone:
+
----
smo clone create -profile prof1 -backup-label full_backup_prof1
-newsid clone1 -label prof1_clone -clonespec C:\\clone_spec\\prof1_clonespec.xml
----
