---
permalink: unix-administration/concept_restoring_database_backup.html
sidebar: sidebar
keywords: 
summary: 'SnapManager for Oracle enables you to restore a database to the state it was when a Snapshot copy was taken. In addition to the file-based restore process, SnapManager supports volume-based fast restore technology, which reduces the restore time significantly compared to other recovery methods. Because backups are created more frequently, the number of logs that need to be applied is reduced, thus reducing the mean-time-to-recovery \(MTTR\) for a database.'
---
= Restoring database backups
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for Oracle enables you to restore a database to the state it was when a Snapshot copy was taken. In addition to the file-based restore process, SnapManager supports volume-based fast restore technology, which reduces the restore time significantly compared to other recovery methods. Because backups are created more frequently, the number of logs that need to be applied is reduced, thus reducing the mean-time-to-recovery (MTTR) for a database.

The following are some of the tasks that you can perform related to restoring and recovering data in databases:

* Perform a file-based restoreor a volume-based restore, which is the fastest method of restoring database backups and is the default that SnapManager uses.
* Restore the entire backup or a portion of it.
+
If you restore a portion of it, you specify a group of tablespaces or a group of data files. You can also restore the control files along with the data or just the control files themselves.

* Recover the data based on either a point in time or on all of the available logs, which stores the last transaction committed to the database.
+
The point in time can be an Oracle System Change Number (SCN) or a date and time (yyyy-mm-dd:hh:mm:ss). SnapManager uses the 24-hour clock.

* Restore from backups on primary storage (local backups).
* Restore and recover the backup by using SnapManager, or use SnapManager to restore the backup and use another tool, such as Recovery Manager (RMAN), to recover the data.
* Restore backups from alternate locations.
* Restore protected backups from secondary storage (remote backups) and from an alternate location by using the restore specification file.

You can restore a backup made by a previous version of SnapManager by using SnapManager 3.0 and later versions.

SnapManager also provides the ability to restore Automatic Storage Management (ASM) databases. An ASM disk group can be shared by multiple databases. Therefore, you cannot revert to an older Snapshot copy of the disk group, because it would revert all of the databases. Traditional restore operation solutions go through the host and require all of the blocks that constitute the database to be moved from the storage system to the host and then back to the storage system. SnapManager relieves this overhead by providing the ability to restore just the required data within the ASM disk group without going through the host.

Administrators can perform restore or recovery operations by using the SnapManager graphical user interface (GUI) or by using the command-line interface (CLI).

*Related information*

xref:concept_database_backup_management.adoc[Backing up databases]

xref:reference_the_smosmsapbackup_restore_command.adoc[The smo backup restore command]
