---
permalink: unix-administration/reference_the_smosmsaprepository_delete_command.html
sidebar: sidebar
keywords: command, delete, repository, store, database, profile, associate, credentials, smo
summary: This command deletes a repository used to store database profiles and associated credentials. You can delete a repository only if there are no profiles in the repository.
---
= The smo repository delete command
:icons: font
:imagesdir: ../media/

[.lead]
This command deletes a repository used to store database profiles and associated credentials. You can delete a repository only if there are no profiles in the repository.

== Syntax

----

        smo repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----

== Parameters

* *-repository*
+
The options that follow -repository specify the details of the database for the repository.

* *-port repo_port*
+
Specifies the TCP port number used to access the database that stores the repository.

* *-dbname repo_service_name*
+
Specifies the name of the database that stores the repository. Use either the global name or the SID.

* *-host repo_host*
+
Specifies the name or IP address of the host computer the repository database runs on.

* *-login*
+
Starts the repository login details.

* *-username repo_username*
+
Specifies the user name needed to access the database that stores the repository.

* *-force*
+
Attempts to force the deletion of the repository, even if there are incomplete operations. SnapManager issues a prompt if there are incomplete operations, asking if you are sure you want to delete the repository.

* *-noprompt*
+
Does not prompt you before deleting the repository. Using the -noprompt option ensures the prompt does not appear, making it easier to delete repositories using a script.

* *-quiet*
+
Displays only error messages on the console. The default is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages on the console.

== Command example

The following example deletes the repository in the SALESDB database.

----
smo repository delete -repository -port 1521 -dbname smorep
-host nila -login -username smofresno -force -verbose
This command will delete repository "smofresno@smorep/nila".
Any resources maintained by the repository must be cleaned up manually.
This may include snapshots, mounted backups, and clones.
Are you sure you wish to proceed (Y/N)?Y
[ INFO] SMO-09201: Dropping existing schema as smofresno
  on jdbc:oracle:thin:@//nila:1521/smorep.
[ INFO] SMO-13048: Repository Delete Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:06.372
[ INFO] SMO-20010: Synchronizing mapping for profiles in
   repository "smofresno@smorep/nila:1521".
[ WARN] SMO-20029: No repository schema exists in "smofresno@smorep/nila:1521".
 Deleting all profile mappings for this repository.
[ INFO] SMO-20012: Deleted stale mapping for profile "TESTPASS".
----
