---
permalink: unix-administration/reference_the_smosmsapcmdfile_command.html
sidebar: sidebar
keywords: cmdfile, command, run, shell, host, limit, number, character, appear, line, smo
summary: You can use the cmdfile command to run any command if the shell on your host limits the number of characters that can appear on a command line.
---
= The smo cmdfile command
:icons: font
:imagesdir: ../media/

[.lead]
You can use the cmdfile command to run any command if the shell on your host limits the number of characters that can appear on a command line.

== Syntax

----

        smo cmdfile
-file file_name
\[-quiet \| -verbose\]
----

You can include the command in a text file and use the smo cmdfile command to execute the command. You can add only one command in a text file. You must not include smo in the command syntax.

NOTE: The smo cmdfile command replaces the smo pfile command. The smo cmdfile is not compatible with the smo pfile command.

== Parameters

* *-file file_name*
+
Specifies the path to text file containing the command you want to execute.

* *-quiet*
+
Specifies that only error messages are displayed in the console. The default is to display error and warning messages.

* *-verbose*
+
Specifies that error, warning, and informational messages are displayed in the console.

== Example

This example creates a profile by including the profile create command in command.txt located at /tmp. You can then run the smo cmdfile command.

The text file contains the following information:

----
profile create -profile SALES1 -repository -dbname SNAPMGRR
-login -username server1_user -password ontap -port 1521 -host server1
-database -dbname SMO -sid SMO -login -username sys -password oracle -port 1521
-host Host2 -osaccount oracle -osgroup db2
----

You can now create the profile by running the smo cmdfile command with the command.txt file:

----
smo cmdfile -file /tmp/command.txt
----
