---
permalink: unix-administration/reference_the_smosmsapbackup_mount_command.html
sidebar: sidebar
keywords: 
summary: 'You can run the backup mount command to mount a backup in order to perform a recover operation by using an external tool.'
---
= The smo backup mount command
:icons: font
:imagesdir: ../media/

[.lead]
You can run the backup mount command to mount a backup in order to perform a recover operation by using an external tool.

== Syntax

----

        smo backup mount 
-profile profile_name 
[-label label \[-data \| -archivelogs\] \| \[-id id\] 
[-host  host] 
\[-from-secondary \{-copy-id id\}\] 
\[-dump\]
[-quiet | -verbose]
----

== Parameters

* *-profile profile_name*
+
Specifies the profile associated with the backup that you want to mount. The profile contains the identifier of the database and other database information.

* *-id guid*
+
Mounts the backup with the specified GUID. The GUID is generated by SnapManager when you create a backup. You can use the smo backup list command to display the GUID for each backup.

* *-label label*
+
Mounts the backup with the specified label.

* *-data*
+
Specifies the data files.

* *-archivelogs*
+
Specifies the archive log files.

* *-from-secondary -copy-id id*
+
Mounts the backup from secondary storage. If this option is not specified, SnapManager mounts the backup from primary storage. You can use this option if the backup is freed.
+
You must specify the -copy-id option whenever you specify the -from-secondary option. If there is more than one backup on the secondary storage system, the -copy-id option is used to specify which backup copy on the secondary storage should be used to mount the backup.
+
NOTE: If you are using Data ONTAP operating in 7-Mode, you must specify a valid value for the -copy-id option. However, if you are using clustered Data ONTAP, the -copy-id option is not required.

* *-host host*
+
Specifies the host on which you want to mount the backup.

* *-dump*
+
Collects the dump files after the successful or failed mount operation.

* *-quiet*
+
Displays only error messages in the console. The default setting is to display error and warning messages.

* *-verbose*
+
Displays error, warning, and informational messages in the console.

NOTE: You must use this command only if you are using an external tool such as Oracle Recovery Manager (RMAN). SnapManager automatically handles the mounting of backups if you use the smo backup restore command to restore the backup. This command displays a list, which shows the paths where the Snapshot copies have been mounted. This list is displayed only when the -verbose option is specified.

== Example

The following example mounts the backup:

----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
SMO-13046 [INFO ]: Operation GUID 8abc013111b9088e0111b908a7560001 starting on Profile SALES1
SMO-08052 [INFO ]: Beginning to connect mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08053 [INFO ]: Finished connecting mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-13037 [INFO ]: Successfully completed operation: Backup Mount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:01:00.981
Operation Id [8abc013111b9088e0111b908a7560001] succeeded.
----

*Related information*

xref:task_mounting_backups.adoc[Mounting backups]
