---
permalink: unix-administration/reference_supported_partition_devices.html
sidebar: sidebar
keywords: 
summary: 'You must know the different partition devices that are supported in SnapManager.'
---
= Supported partition devices
:icons: font
:imagesdir: ../media/

[.lead]
You must know the different partition devices that are supported in SnapManager.

The following table provides partition information and how it can be enabled for different operating systems:

|===
| Operating system| Single partition| Multiple partition| Non-partition devices| File system or RAW devices
a|
Red Hat Enterprise Linux 5x or

Oracle Enterprise Linux 5x

a|
Yes
a|
No
a|
No
a|
ext3*
a|
Red Hat Enterprise Linux 6xor

Oracle Enterprise Linux 6x

a|
Yes
a|
No
a|
No
a|
ext3 or ext4*
a|
SUSE Linux Enterprise Server 11
a|
Yes
a|
No
a|
No
a|
ext3*
a|
SUSE Linux Enterprise Server 10
a|
No
a|
No
a|
Yes
a|
ext3***
a|
Red Hat Enterprise Linux 5x or lateror

Oracle Enterprise Linux 5x or later

a|
Yes
a|
No
a|
Yes
a|
ASM with ASMlib**
a|
SUSE Linux Enterprise Server 10 SP4or

SUSE Linux Enterprise Server 11

a|
Yes
a|
No
a|
Yes
a|
ASM with ASMlib**
a|
SUSE Linux Enterprise Server 10 SP4 or lateror

SUSE Linux Enterprise Server 11

a|
Yes
a|
No
a|
No
a|
ASM without ASMlib****
a|
*For a non-MPIO environment, enter the following command: sfdisk -uS -f -L -q /dev/ device_name

For an MPIO environment, enter the following commands:

* sfdisk -uS -f -L -q /dev/ device_name
* kpartx -a -p p /dev/mapper/ device_name

a|
**For a non-MPIO environment, enter the following command: fdisk /dev/device_name

For an MPIO environment, enter the following commands:

* fdisk /dev/mapper/device_name
* kpartx -a -p p /dev/mapper/device_name

a|
***Not applicable.

a|
****For an MPIO environment, enter the following command:

* kpartx -a -p p /dev/$kernel

|===
For more information on the operating system versions supported, refer to the Interoperability Matrix.
