---
permalink: unix-administration/task_ensuring_that_asm_discovers_imported_disks.html
sidebar: sidebar
keywords: automatic, storage, management, asm, nfs, environment, install, snapmanager, discover, import, disk, snapmanager
summary: If you are using Automatic Storage Management \(ASM\) in an NFS environment, after installing SnapManager, you must ensure that ASM can discover the disks imported by SnapManager. You can do this by adding the path of the ASM directory to the ASM_DISKSTRING parameter.
---
= Ensuring that ASM discovers imported disks
:icons: font
:imagesdir: ../media/

[.lead]
If you are using Automatic Storage Management (ASM) in an NFS environment, after installing SnapManager, you must ensure that ASM can discover the disks imported by SnapManager. You can do this by adding the path of the ASM directory to the ASM_DISKSTRING parameter.

You can use Oracle tools to edit the ASM_DISKSTRING parameter. For information about editing ASM_DISKSTRING, see the Oracle documentation.

The ASM disk path /opt/NetApp/smo/mnt/*/*/disk*' must be added to the existing path defined in the ASM_DISKSTRING parameter. For example, if the path defined in ASM_DISKSTRING was /mnt/my-asm-disks/dir1/disk*, after adding the ASM disk path, the updated path will be '/mnt/my-asm-disks/dir1/disk*,/opt/NetApp/smo/mnt/*/*/disk*'.

NOTE: The ASM_DISKSTRING parameter must match only the ASM disk files and not any other files.

* The first asterisk (*) indicates the name generated by SnapManager for the root mount point.
* The second * indicates the directory within the mount point.
* The third * indicates the name of the NFS file.

You must ensure that the * matches the topology of your NFS file system, if the disk is mounted in the directories under /opt/NetApp/smo/mnt/<smo-generated-name>/.

. If you are using ASM disks with NFS in the Network Attached Storage (NAS) environment, edit the ASM_DISKSTRING parameter so that it points to the current ASM directory path.
+
If the ASM disks mount point is /mnt/my-asm-disks/*/disk*, after editing ASM_DISKSTRING, the updated path is /opt/NetApp/smo/mnt/my-asm-disks-20081012/disk1.nfs. The ASM_DISKSTRING parameter is in the form /opt/NetApp/smo/mnt/*/disk*.

 ** The first * matches my-asm-disks-20081012.
 ** The disk* matches disk1.nfs.
After editing the ASM_DISKSTRING parameter, the results of ASM discovering the disks imported by SnapManager are as follows:
 ** Clone of ASM on NFS disk1 is /opt/NetApp/smo/mnt/-mnt-my-asm-disks-20081012/dir1/disk1.nfs.
 ** Clone of ASM on NFS disk2 is /opt/NetApp/smo/mnt/-mnt-my-asm-disks-20081012/dir1/disk2.nfs.
The ASM_DISKSTRING parameter is in the form /opt/NetApp/smo/mnt/*/*/disk*.
 ** The first * matches -mnt-my-asm-disks-20081012.
 ** The second * matches dir1.
 ** The third * matches disk1.nfs and disk2.nfs.

. If you are using ASM disks in the Storage Area Network (SAN) environment, depending on the environment perform one of the following:
+
[options="header"]
|===
| If you are using ASM disks with...| Then...
a|
ASMLib over FCP and iSCSI on Linux
a|
Change the permission of the Oracle software owner and primary group of the user by using only the character device.    The ASM_DISKSTRING path must be ASM DISKSTRING = ORCL:*.
a|
FCP and iSCSI on AIX
a|
Add the path name for the ASM_DISKSTRING parameter until the ASM directory path.    The ASM_DISKSTRING path must be ASM DISKSTRING = /dev/hdsk/*, where * indicates the ASM disk name.
a|
FCP and iSCSI on Solaris
a|
Add the path name for the ASM_DISKSTRING parameter until the ASM directory path.    The ASM_DISKSTRING path must be ASM DISKSTRING = /dev/rdsk/*, where * indicates the ASM disk name.
+
|===

http://www.oracle.com/technetwork/indexes/documentation/index.html[Oracle Documentation: www.oracle.com/technetwork/indexes/documentation/index.html]
