---
permalink: unix-installation-cmode/reference_product_overview.html
sidebar: sidebar
keywords: 
summary: 'SnapManager for Oracle automates and simplifies the complex, manual, and time-consuming processes associated with the backup, recovery, and cloning of Oracle databases. You can use SnapManager with Data ONTAP SnapMirror technology to create copies of backups on another volume and with Data ONTAP SnapVault technology to archive backups efficiently to disk.'
---
= Product overview
:icons: font
:imagesdir: ../media/

[.lead]
SnapManager for Oracle automates and simplifies the complex, manual, and time-consuming processes associated with the backup, recovery, and cloning of Oracle databases. You can use SnapManager with Data ONTAP SnapMirror technology to create copies of backups on another volume and with Data ONTAP SnapVault technology to archive backups efficiently to disk.

SnapManager integrates with native Oracle technologies such as Oracle Real Application Clusters (Oracle RAC), Automatic Storage Management (ASM), and Direct NFS across FC, iSCSI, and NFS protocols. Optionally, backups created by using SnapManager can be cataloged with Oracle Recovery Manager (RMAN) to preserve the backup information; these backups can be used later in block-level restore or tablespace point-in-time recovery operations.

== SnapManager highlights

SnapManager features seamless integration with Oracle databases on the UNIX host and with NetApp Snapshot, SnapRestore, and FlexClone technologies on the back end. It offers an easy-to-use user interface (UI) as well as command-line interface (CLI) for administrative functions.

SnapManager enables you to perform the following database operations and manage data efficiently:

* Creating space-efficient backups on primary or secondary storage
+
SnapManager enables you to back up the data files and archive log files separately.

* Scheduling backups
* Restoring full or partial databases by using a file-based or volume-based restore operation
* Recovering databases by discovering, mounting, and applying archive log files from backups
* Pruning archive log files from archive log destinations when creating backups of only the archive logs
* Retaining a minimum number of archive log backups automatically by retaining only the backups that contain unique archive log files
* Tracking operation details and generating reports
* Verifying backups to ensure that backups are in a valid block format and that none of the backed-up files are corrupted
* Maintaining a history of operations performed on the database profile
+
A profile contains information about the database to be managed by SnapManager.

* Protecting backups on the secondary storage systems.
* Creating space-efficient clones of backups on primary or secondary storage
+
SnapManager enables you to split a clone of a database.
